Fix Python lint commands in contribution guide
lint_py2 and lint_py3 are no longer defined in the tox.ini config file. When
I try the currently suggested commands, I get the following error message:

  ERROR: unknown environment 'lint_py2'

py27-lint and py3-lint appear to be the replacements.